### ISSUE TITLE
Change the star timing units to seconds

### ISSUE THREAD

**Issue by getkey** [getkey/ble#26]
Seconds seem to be more intuitive than what we have currently: milliseconds (see https://discord.com/channels/526188679006388254/680197233337172092/785193162246586368 and the uploads above the Discord message).

**Comment by matt-ross16** [comment]
I would be willing to get this implemented for you, but I've tried to find where the time it takes to complete a level is even displayed, let alone calculated.

Could you possibly point me in the right direction?

**Comment by getkey** [comment]
Gladly!

This is the file for the star timings interface that appears in the top-right side of the editor: https://github.com/getkey/ble/blob/e16180aadae2a3e1c7af0450719990edff42cdb4/src/components/LevelParamsBox.tsx#L67-L80
https://github.com/getkey/ble/blob/e16180aadae2a3e1c7af0450719990edff42cdb4/src/components/LevelParamsBox.tsx#L31

![image](https://user-images.githubusercontent.com/6908397/101491091-9cca9600-3963-11eb-9667-44bcd798b96d.png)

And this is where the logic actually happens. Times must be stored in ms because that's how they are defined in the level file format, so a conversion has to happen before.

https://github.com/getkey/ble/blob/e16180aadae2a3e1c7af0450719990edff42cdb4/src/models/Level.ts#L13-L28

**Comment by matt-ross16** [comment]
Finding time to do this now, however, I'm having some issues installing the dependencies with `yarn`

![image](https://user-images.githubusercontent.com/37879416/101566274-b76d3100-399c-11eb-8146-6c4316fccf01.png)

**Comment by getkey** [comment]
You might be using [this command](https://hadoop.apache.org/docs/current/hadoop-yarn/hadoop-yarn-site/YarnCommands.html) which has the same name but is unrelated to the [Yarn Package Manager](https://classic.yarnpkg.com/lang/en/). Try `yarn --help` to get more info, if you have the right one, it will display `Visit https://yarnpkg.com/en/docs/cli/ to learn more about Yarn.` at the bottom.

Since you are on Ubuntu, you can install [`yarnpkg`](https://packages.ubuntu.com/groovy/yarnpkg) from apt or [install it directly from the website](https://classic.yarnpkg.com/en/docs/install).

Also I should mention that though yarn 2.x exists, this project uses yarn 1.x. Both links above are for this version. 🙂 (you can use `yarn --version` to check which version you have)

**Comment by matt-ross16** [comment]
Ok thanks for the info :) I definitely had the wrong package set up. Installing now

**Comment by matt-ross16** [comment]
While it looks like I got a successful compilation, proceeding to localhost:8080 leaves me with a blank page. Should I be expecting some kind of output?

![image](https://user-images.githubusercontent.com/37879416/101676062-a36f1100-3a28-11eb-8fe1-a4ba89692c74.png)
![image](https://user-images.githubusercontent.com/37879416/101676006-8e927d80-3a28-11eb-9b9a-c3f39cdae969.png)
![image](https://user-images.githubusercontent.com/37879416/101676231-e4ffbc00-3a28-11eb-8ecb-b41c6526a97f.png)
![image](https://user-images.githubusercontent.com/37879416/101676251-ecbf6080-3a28-11eb-9ecc-0264179915b8.png)

**Comment by getkey** [comment]
That's weird. Do you have error messages in your console?
The page has the proper title so at least the HTML is downloaded by your browser but the JS might not.

**Comment by matt-ross16** [comment]
Oh I see. Yes, I am getting some browser errors.

![image](https://user-images.githubusercontent.com/37879416/101942867-37bbae00-3bb8-11eb-9a72-8c86840c6cbb.png)

Currently using Firefox v 83.0 (it's up to date)

Should I be trying a different browser?

**Comment by getkey** [comment]
Looks like Firefox isn't able to use your GPU. Check `about:support`, it will tell you what GPU driver it's using (or not).
You can also try the page out on Chromium and if it doesn't work get similar debug information in `chrome://gpu`.

Btw, can you play desktop games? If you can with normal FPS and the page works fine on Chrome, then the culprit is Firefox. Otherwise, I'd place my bets on a driver issue. :slightly_smiling_face:

If Firefox is the problem, set `layers.acceleration.force-enabled` to true in `about:config`, it forces Firefox to use the GPU even on configurations that have not been tested by the Mozilla team.
If it's a driver issue, mess around Ubuntu's GUI for listing and changing your GPU drivers.

**Comment by matt-ross16** [comment]
Thanks for pointing me in the right direction! Firefox was needing some adjustments, so I'm ready to start this fix now :)

**Comment by matt-ross16** [comment]
While I've been able to adjust the values for the timing, I have yet to find a way to "hijack" the timings in the text boxes as they are saved to the JSON file. Tracking down where the values are extracted is proving difficult.

**Comment by getkey** [comment]
There is no need to hijack the timings when the JSON is saved.

The timings in the internal state of the program can stay in milliseconds, like in the JSON. But in the interface, they must be converted to seconds. When timings are changed in the interface (for example to 4s), what must be stored is 4000.

You can do the `* 1000` here https://github.com/getkey/ble/blob/e16180aadae2a3e1c7af0450719990edff42cdb4/src/components/LevelParamsBox.tsx#L46-L51

And of course, https://github.com/getkey/ble/blob/e16180aadae2a3e1c7af0450719990edff42cdb4/src/components/LevelParamsBox.tsx#L72 and https://github.com/getkey/ble/blob/e16180aadae2a3e1c7af0450719990edff42cdb4/src/components/LevelParamsBox.tsx#L77, you will need to do a `/ 1000`.

**Comment by matt-ross16** [comment]
Interesting. So far I've tried to multiply the values by 1000 in `LevelParamsBox`, but it hasn't seemed to have an effect on the value being saved within the JSON. Testing some hard coding to see if it's the method that I'm going about doing.

**Comment by getkey** [comment]
> Doing the multiplication in the on2StarChange function will take the number you type into the text input and INSTANTLY multiply it by 1000

This is why it's important to **also** do the `/ 1000` in `value` here https://github.com/getkey/ble/blob/e16180aadae2a3e1c7af0450719990edff42cdb4/src/components/LevelParamsBox.tsx#L74 and https://github.com/getkey/ble/blob/e16180aadae2a3e1c7af0450719990edff42cdb4/src/components/LevelParamsBox.tsx#L79 (my bad, in my previous message I put the wrong line number).

That will avoid the multiplication happening each time and having the number going to the moon. :sweat_smile:

**Comment by matt-ross16** [comment]
Oh my goodness yes! That makes a LOT more sense. I'm so silly haha!

**Comment by matt-ross16** [comment]
Ok down to what I believe is the final decision: which would you prefer to represent seconds?

Only having an 's'
![image](https://user-images.githubusercontent.com/37879416/101965191-cabd0e00-3be1-11eb-8df4-e64322df12bd.png)

or using 'secs'
![image](https://user-images.githubusercontent.com/37879416/101965084-79ad1a00-3be1-11eb-934a-3e72b2fd7784.png)

**Comment by getkey** [comment]
Nice! :smile: 

Usually I would have said just 's' because it's shorter but here I think 'secs' looks better in this vertical layout. So 'secs' please :slightly_smiling_face:

**Comment by matt-ross16** [comment]
Deal!
