### ISSUE TITLE
Expose the `rightFacing` parameter of the doors

### ISSUE THREAD

**Issue by getkey** [getkey/ble#68]
This parameter can flip vertically the texture of doors. The game supports it, it's used in some official levels (**Choice** on the top of my head). But the editor doesn't support the feature.

https://github.com/getkey/bombhopperio-level-tools/blob/e9ce9beaa02b9f79349da370b623a9b9253b8571/src/entity.schema.json#L192-L194

**Comment by lejara** [comment]
hello!
may i work on this?

**Comment by getkey** [comment]
Yes gladly!

To get you started, there is a very similar feature that you can have a look at and copy https://github.com/getkey/ble/blob/8ad099879d85ecc295beeb91f3f0b364ecf3ab48/src/models/StaticParams.ts and https://github.com/getkey/ble/blob/8ad099879d85ecc295beeb91f3f0b364ecf3ab48/src/components/StaticParam.tsx

You'll need to replace the model here https://github.com/getkey/ble/blob/8ad099879d85ecc295beeb91f3f0b364ecf3ab48/src/models/Door.ts#L18-L20 and you can hook up the UI here https://github.com/getkey/ble/blob/8ad099879d85ecc295beeb91f3f0b364ecf3ab48/src/components/ParamsBox.tsx

Lemme know if you need more guidance :wink:
